### ISSUE TITLE
SHA1 Hashes for comparison to amcache?

### ISSUE THREAD

**Issue by timetology** [AndrewRathbun/VanillaWindowsReference#2]
Hello,

Any chance you'd be willing to add sha1 hashes in addition to md5 and sha25?. This would allow for easy comparison to amcache output.

**Comment by AndrewRathbun** [comment]
> Hello,
> 
> Any chance you'd be willing to add sha1 hashes in addition to md5 and sha25?. This would allow for easy comparison to amcache output.

I can definitely add that moving forward. Going back and recreating 200+ VMs to redo everything I've done would be a massive pain, as you can imagine! 

That being said, any special requests for past versions to redo this with the SHA1 values added?

**Comment by timetology** [comment]
Thanks for the quick reply! I don't have any specific past versions to request, maybe just the latest version for each category (10/11/Server?

**Comment by timetology** [comment]
Reopening, closed by mistake

**Comment by AndrewRathbun** [comment]
> Thanks for the quick reply! I don't have any specific past versions to request, maybe just the latest version for each category (10/11/Server?

Sure. I'll do that this week. Stay tuned!

**Comment by AndrewRathbun** [comment]
https://github.com/AndrewRathbun/VanillaWindowsReference/commit/bfc9059d978892a5f080cc60d95780405b10452c

This is done

**Comment by AndrewRathbun** [comment]
I am sorry, I just realized today I was using an old command all this time on the recent months' CSVs. I've updated my local commands that I reference every month to ensure the right command is used from here on out. My apologies!
