### ISSUE TITLE
duplicate?

### ISSUE THREAD

**Issue by bittib010** [AndrewRathbun/VanillaWindowsReference#4]
I think there may be a duplicate: /Windows10/1709/W10_1709_Pro_20171114_16299.64 and  /Windows10/1709/W10_1709_Pro_16299.64...
System infos are identical. Caught it when creating filetree gui for the files... they popped up with double everything.. :)

The naming convention on the parent folder of the second is also off, which gave it away.

**Comment by AndrewRathbun** [comment]
I think you're right. Unfortunately, I don't have access to these ISOs anymore, so I can't go back and correct it.

**Comment by bittib010** [comment]
As they are identical, maybe remove one from the repo?

**Comment by AndrewRathbun** [comment]
> As they are identical, maybe remove one from the repo?

This is done, as seen above.
